packages:
  - packages/*

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

catalogs:
  dev:
    '@types/node': ^24.1.0
    '@typescript-eslint/utils': ^8.38.0
    '@vitest/coverage-v8': ^3.2.4
    ansis: ^4.1.0
    eslint: ^9.32.0
    jiti: ^2.5.1
    json-schema-to-typescript-lite: ^15.0.0
    prettier: ^3.6.2
    svelte: ^5.37.0
    tinyglobby: ^0.2.14
    tsdown: ^0.13.0
    tsx: ^4.20.3
    turbo: ^2.5.5
    typescript: ^5.8.3
    vitest: ^3.2.4

  prod:
    '@eslint/js': ^9.32.0
    '@stylistic/eslint-plugin': ^5.2.2
    eslint-config-flat-gitignore: ^2.1.0
    eslint-config-prettier: ^10.1.8
    eslint-plugin-import-x: ^4.16.1
    eslint-plugin-jsdoc: ^52.0.0
    eslint-plugin-jsonc: ^2.20.1
    eslint-plugin-perfectionist: ^4.15.0
    globals: ^16.3.0
    typescript-eslint: ^8.38.0
